### ISSUE TITLE
Fatal error: Call to undefined function browser_bin() in /htdocs/cm/tcrt-bundler_src.php on line 16

### ISSUE THREAD

**Issue by svnt** [alexkazik/tapecart-browser#1]
What  is this browser_bin() function?

Can't pack a cart due the error:

Fatal error: Call to undefined function browser_bin() in //htdocs/cm/tcrt-bundler_src.php on line 16

**Comment by alexkazik** [comment]
The php file in the src directory is only a template. 
If you run the Haskell program a new one (including the browser_bin function) will be created in the build directory.

**Comment by svnt** [comment]
Build want run:  Unable to parse cabal file: FromString "This package requires at least Cabal version 2.0" Nothing

$ cabal -V
cabal-install version 1.22.6.0
using version 1.22.5.0 of the Cabal library 

Any idea how to fix this?

I'm running Linux Mint:

Linux svent 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alexkazik** [comment]
Or use the already compiled file from the releases page.

Try installing the latest stack[1], it should install everything required.

[1]: https://docs.haskellstack.org/en/stable/README/

**Comment by svnt** [comment]
Oh yes. I'll use the release. :)
Thank you!
