### ISSUE TITLE
8MB mod

### ISSUE THREAD

**Issue by dikdom** [alexkazik/tapecart-browser#2]
Hello Alex,

I have made some modifications in your project, you _might_ be interested in.
First, I have modded the firmware of the Tapecart, that it reports the size of the added chip and not a precompiled value (2MB). If you attach a 16MB flash, then it reports 16MB, etc...
Then I have modded your code, to handle up to 255 entries and 8MB of storage. Not a big deal, but I'm not a haskell pro so it was a major stuff for me.
Are you interested in?

**Comment by alexkazik** [comment]
If it's still working on the original cart then sure I'm interested.

**Comment by dikdom** [comment]
If you compile an image less than 2MB, then it works. 
I will finalize the code and will push it into my forked repo. I can send a pull request to your (master) repo, but actually it is not a big deal. Let me know how you would like to get it.

**Comment by dikdom** [comment]
Changes pushed to my fork, but currently cannot merge with your latest changes in stack.yaml. See other issue...

**Comment by alexkazik** [comment]
After thinking about it I decided to not to put it into my master because the tapecart is specified to be always 2MB to make sure that any software written for the tapecart runs on every version. 

But I'm happily ass it as a branch or simply link from the readme to your version.

**Comment by dikdom** [comment]
Ok, I understand. Though you may put a switch in the php script which enables it to build large tcrt, by default it could build only max 2MB. 
Anyway, I'm OK with your approach also.
