### ISSUE TITLE
Cannot build stack

### ISSUE THREAD

**Issue by dikdom** [alexkazik/tapecart-browser#3]
After fetching the latest stack.yaml into my repo, I cannot build the stack, exec the tapecart-browser stack..

> $ stack test
Could not parse '/home/sanyi/devel/tapecart-browser/stack.yaml':
Aeson exception:
Error in $['extra-deps'][0]: failed to parse field 'extra-deps': failed to parse field 'github': key "github" not present
See http://docs.haskellstack.org/en/stable/yaml_configuration/
sanyi@sandor-pc:~/devel/tapecart-browser$ stack --version | head
Version 1.7.1 x86_64
Compiled with:
> - Cabal-2.2.0.1
> - Glob-0.9.2
> - HUnit-1.6.0.0
> - QuickCheck-2.11.3
> - StateVar-1.1.1.1
> - aeson-1.3.1.1
> - aeson-compat-0.3.8
> - annotated-wl-pprint-0.7.0

**Comment by dikdom** [comment]
As a matter of fact the same problem happens with a brand new cloned repo:

> sanyi@sandor-pc:\~/devel$ mkdir tapecart-browser-new
sanyi@sandor-pc:\~/devel$ cd tapecart-browser-new/
sanyi@sandor-pc:\~/devel/tapecart-browser-new$ git clone https://github.com/alexkazik/tapecart-browser.git
Cloning into 'tapecart-browser'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 127 (delta 3), reused 5 (delta 2), pack-reused 118
Receiving objects: 100% (127/127), 40.57 KiB | 461.00 KiB/s, done.
Resolving deltas: 100% (61/61), done.
sanyi@sandor-pc:\~/devel/tapecart-browser-new$ cd tapecart-browser/
sanyi@sandor-pc:\~/devel/tapecart-browser-new/tapecart-browser$ stack build
Could not parse '/home/sanyi/devel/tapecart-browser-new/tapecart-browser/stack.yaml':
Aeson exception:
Error in $['extra-deps'][0]: failed to parse field 'extra-deps': failed to parse field 'github': key "github" not present
See http://docs.haskellstack.org/en/stable/yaml_configuration/

**Comment by alexkazik** [comment]
First, I'm sorry for the late reply, I'm distracted by being on vacation.
You need a more recent version of stack (https://tech.fpcomplete.com/haskell/get-started).

But the only changes are to use a newer version of lts, stack and my assembler.

**Comment by dikdom** [comment]
Thanks, it fixed the build ('stack upgrade --binary-only' was missing)
